# Generated by Django 5.2.17 on 2026-09-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_scope1_12_domains'),
        ('leases', '0001_scope1_12_domains'),
        ('parties', '0001_scope0_foundation'),
        ('property', '0002_alter_asset_id_alter_building_id_alter_contractor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='charge',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='parties.party'),
        ),
        migrations.AddField(
            model_name='charge',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='property.space'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.party'),
        ),
        migrations.AddField(
            model_name='charge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='billing.charge'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice'),
        ),
    ]
