# Generated by Django 5.2.17 on 2026-09-15 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(db_index=True, max_length=64)),
                ('operation', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('success', 'Uğurlu'), ('error', 'Xəta'), ('dead', 'Dead-letter')], max_length=16)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(max_length=128)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('pending', 'Gözləyir'), ('success', 'Uğurlu'), ('error', 'Xəta'), ('dead', 'Dead-letter')], default='pending', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='integration_entity__964f6b_idx')],
                'unique_together': {('system', 'external_id')},
            },
        ),
    ]
