# Generated by Django 5.2.17 on 2026-09-15 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_scope0_foundation'),
        ('property', '0002_alter_asset_id_alter_building_id_alter_contractor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractors', to='parties.party'),
        ),
        migrations.AddField(
            model_name='space',
            name='commercial_status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('reserved', 'Reserved'), ('contracted', 'Contracted'), ('active', 'Active'), ('notice', 'Notice')], default='vacant', max_length=24),
        ),
        migrations.AddField(
            model_name='space',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='operational_status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('blocked', 'Blocked')], default='available', max_length=24),
        ),
        migrations.AddField(
            model_name='space',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='space',
            name='rentable_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ParkingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('resident', 'Resident'), ('employee', 'Employee'), ('visitor', 'Visitor'), ('temporary', 'Temporary')], default='resident', max_length=24)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_assignments', to='parties.party')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='property.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_zones', to='property.building')),
            ],
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='property.parkingzone'),
        ),
        migrations.CreateModel(
            name='UtilityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_code', models.CharField(max_length=64)),
                ('utility_type', models.CharField(choices=[('electric', 'Electric'), ('water', 'Water'), ('gas', 'Gas'), ('other', 'Other')], default='electric', max_length=16)),
                ('unit', models.CharField(default='kWh', max_length=16)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='property.space')),
            ],
            options={
                'unique_together': {('space', 'meter_code')},
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=3, max_digits=14)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='property.utilitymeter')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='parkingspot',
            unique_together={('zone', 'code')},
        ),
    ]
