# Generated by Django 5.2.17 on 2026-09-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_scope1_12_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='base_rent_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AZN / m² / ay (istinad)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='fit_out_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='space',
            name='service_charge_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AZN / m² / ay (istinad)', max_digits=12, null=True),
        ),
    ]
