# Generated by Django 5.2.17 on 2026-09-15 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_guest_id_alter_guestvisit_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guestvisit',
            name='created_by_portal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_guest_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestvisit',
            name='expected_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestvisit',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='guestvisit',
            name='pre_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guestvisit',
            name='status',
            field=models.CharField(choices=[('pre_registered', 'Əvvəlcədən qeyd'), ('waiting', 'Gözləyir'), ('inside', 'İçəridə'), ('left', 'Çıxış'), ('cancelled', 'Ləğv')], default='waiting', max_length=16),
        ),
    ]
