# Generated by Django 5.2.17 on 2026-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_visitor_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='fin_code',
            field=models.CharField(blank=True, db_index=True, help_text='Şəxsiyyət vəsiqəsindəki seriya nömrəsi', max_length=32, verbose_name='Seriya nömrəsi'),
        ),
    ]
