# Generated by Django 5.2.17 on 2026-09-21 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_scope0_foundation'),
        ('residents', '0011_announcement_visibility_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='company',
            field=models.ForeignKey(blank=True, help_text='COMPANY / TARGETED üçün məcburi; BUILDING üçün boş', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='residents.residentcompany'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='TARGETED görünürlük üçün', related_name='targeted_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('building', 'Bina-ümumi'), ('company', 'Şirkət'), ('targeted', 'Hədəflənmiş')], default='building', max_length=16),
        ),
    ]
