# Generated by Django 5.2.17 on 2026-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_accessevent_id_alter_residentcompany_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentcompany',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Operator / City Point özü — rezident siyahısına düşmür'),
        ),
    ]
