# Generated by Django 5.2.17 on 2026-09-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_company_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='axtrax_employee_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='card_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='employee_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='residentemployee',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='İşdən çıxış / AxTrax-dan silinmə vaxtı — tarixçəyə qədər baxış üçün', null=True),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='residents.residentemployee'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['employee', 'occurred_at'], name='residents_a_employe_b59fad_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['occurred_at'], name='residents_a_occurre_da96ee_idx'),
        ),
        migrations.AddIndex(
            model_name='residentemployee',
            index=models.Index(fields=['company', 'is_active', 'full_name'], name='residents_r_company_85df6f_idx'),
        ),
    ]
