# Generated by Django 5.2.17 on 2026-09-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_access_retention_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentemployee',
            name='id_document',
            field=models.FileField(blank=True, help_text='Şəxsiyyət vəsiqəsi nüsxəsi (kart sifarişi üçün)', upload_to='employees/id/%Y/%m/'),
        ),
    ]
