# Generated by Django 5.2.17 on 2026-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_reader_name_full'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rapidcardswipealert',
            new_name='residents_r_employe_3f25ab_idx',
            old_name='residents_r_employe_7a2c1d_idx',
        ),
        migrations.RenameIndex(
            model_name='rapidcardswipealert',
            new_name='residents_r_acknowl_5c731b_idx',
            old_name='residents_r_acknowl_9b4e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='shaftaccessalert',
            new_name='residents_s_acknowl_b03a69_idx',
            old_name='residents_s_acknowl_shaft_idx',
        ),
        migrations.AlterField(
            model_name='residentemployee',
            name='access_level',
            field=models.CharField(choices=[('1', 'Səviyyə 1 — turn_back yox'), ('2', 'Səviyyə 2 — turn_back icazəli')], default='1', help_text='AxTraxNG access group: 1 = turn_back yox; 2 = turn_back icazəli', max_length=8),
        ),
    ]
