# Generated by Django 5.2.17 on 2026-09-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0011_announcement_visibility_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentemployee',
            name='card_order_status',
            field=models.CharField(blank=True, choices=[('none', '—'), ('submitted', 'Göndərilib'), ('under_review', 'Yoxlanılır'), ('approved', 'Təsdiqlənib'), ('prepared', 'Hazırlanır'), ('issued', 'Verilib'), ('rejected', 'Rədd'), ('cancelled', 'Ləğv')], default='none', max_length=16),
        ),
    ]
