# Generated by Django 5.2.17 on 2026-09-15 06:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0002_alter_accessevent_id_alter_residentcompany_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('party_type', models.CharField(choices=[('organization', 'Təşkilat'), ('person', 'Fiziki şəxs')], default='organization', max_length=16)),
                ('legal_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=64, verbose_name='VÖEN')),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Aktiv'), ('inactive', 'Qeyri-aktiv'), ('blocked', 'Bloklanıb')], default='active', max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('legacy_resident_company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to='residents.residentcompany')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('person_kind', models.CharField(choices=[('resident_employee', 'Rezident əməkdaş'), ('contact', 'Əlaqə şəxsi'), ('visitor', 'Qonaq'), ('contractor_employee', 'Podratçı əməkdaş'), ('staff', 'City Point əməkdaş')], default='contact', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='residents.residentemployee')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='parties.party')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('resident', 'Rezident'), ('prospect', 'Prospect'), ('supplier', 'Təchizatçı'), ('contractor', 'Podratçı'), ('partner', 'Partnyor'), ('other', 'Digər')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='parties.party')),
            ],
            options={
                'unique_together': {('party', 'role')},
            },
        ),
    ]
