# Generated by Django 5.2.17 on 2026-09-15 07:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_scope0_foundation'),
        ('property', '0002_alter_asset_id_alter_building_id_alter_contractor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('negotiation', 'Negotiation'), ('approved', 'Approved'), ('signed', 'Signed'), ('active', 'Active'), ('expiring', 'Expiring'), ('renewed', 'Renewed'), ('amended', 'Amended'), ('terminated', 'Terminated')], default='draft', max_length=24)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='AZN', max_length=8)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billing_active', models.BooleanField(default=False)),
                ('portal_eligible', models.BooleanField(default=False)),
                ('access_eligible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('parent_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='leases.lease')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='parties.party')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='property.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='leases.lease')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_lines', to='property.space')),
            ],
        ),
    ]
