# Generated by Django 5.2.17 on 2026-09-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_scope1_12_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('once', 'Once')], default='monthly', max_length=16),
        ),
    ]
