# Generated by Django 5.2.17 on 2026-09-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_scope1_12_domains'),
        ('tickets', '0003_ticketstatusevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'ticket categories'},
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='pause_on_waiting',
            field=models.BooleanField(default=True, help_text='Waiting statusunda SLA saatı dayansın'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='enrichment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tickets', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resident_priority_suggestion',
            field=models.CharField(blank=True, choices=[('low', 'Aşağı'), ('normal', 'Normal'), ('high', 'Yüksək'), ('critical', 'Kritik')], max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('incident', 'Hadisə'), ('service_request', 'Xidmət sorğusu'), ('complaint', 'Şikayət'), ('commercial', 'Kommersiya sorğusu')], default='incident', max_length=32),
        ),
        migrations.AddField(
            model_name='ticket',
            name='waiting_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='priority',
            field=models.CharField(choices=[('low', 'Aşağı'), ('normal', 'Normal'), ('high', 'Yüksək'), ('critical', 'Kritik')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Aşağı'), ('normal', 'Normal'), ('high', 'Yüksək'), ('critical', 'Kritik')], default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('sent', 'Yeni'), ('assigned', 'Təyin edildi'), ('accepted', 'Qəbul edildi'), ('in_progress', 'İcradadır'), ('waiting', 'Gözləmədə'), ('resolved', 'Həll edildi'), ('closed', 'Bağlandı'), ('cancelled', 'Ləğv edildi'), ('reopened', 'Yenidən açıldı')], default='sent', max_length=24),
        ),
        migrations.AlterField(
            model_name='ticketstatusevent',
            name='to_status',
            field=models.CharField(choices=[('sent', 'Yeni'), ('assigned', 'Təyin edildi'), ('accepted', 'Qəbul edildi'), ('in_progress', 'İcradadır'), ('waiting', 'Gözləmədə'), ('resolved', 'Həll edildi'), ('closed', 'Bağlandı'), ('cancelled', 'Ləğv edildi'), ('reopened', 'Yenidən açıldı')], max_length=24),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketdepartment'),
        ),
        migrations.CreateModel(
            name='TicketQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='tickets.ticketdepartment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketqueue'),
        ),
        migrations.CreateModel(
            name='TicketRoutingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketdepartment')),
                ('from_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketqueue')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_events', to='tickets.ticket')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketdepartment')),
                ('to_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketqueue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_description_min', models.PositiveSmallIntegerField(default=0, help_text='Other üçün minimum təsvir uzunluğu; 0 = yoxdur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tickets.ticketcategory')),
            ],
            options={
                'verbose_name_plural': 'ticket subcategories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_priority', models.CharField(choices=[('low', 'Aşağı'), ('normal', 'Normal'), ('high', 'Yüksək'), ('critical', 'Kritik')], default='normal', max_length=16)),
                ('wo_eligible', models.BooleanField(default=False)),
                ('crm_eligible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='tickets.slapolicy')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='tickets.ticketdepartment')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='tickets.ticketqueue')),
                ('subcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rule', to='tickets.ticketsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketsubcategory'),
        ),
    ]
