# Generated by Django 5.2.17 on 2026-09-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_employee_card_order'),
        ('tickets', '0004_ticket_taxonomy_routing_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='related_employee',
            field=models.ForeignKey(blank=True, help_text='Kart sifarişi / əməkdaş onboarding ticket-i', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_order_tickets', to='residents.residentemployee'),
        ),
    ]
