# Generated by Django 5.2.17 on 2026-09-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_employee_card_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='waiting_reason_code',
            field=models.CharField(blank=True, choices=[('resident_response', 'Rezident cavabı'), ('spare_part', 'Ehtiyat hissə'), ('contractor', 'Podratçı'), ('approval', 'Təsdiq'), ('other', 'Digər')], default='', max_length=32),
        ),
    ]
