# Generated by Django 5.2.17 on 2026-09-15 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_scope0_foundation'),
        ('property', '0002_alter_asset_id_alter_building_id_alter_contractor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('negotiation', 'Negotiation'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=24)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=16)),
                ('expected_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('walk_in', 'Walk-in'), ('referral', 'Referral'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('converted', 'Converted')], default='new', max_length=24)),
                ('message', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('interested_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='property.space')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='parties.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
