# Generated by Django 5.2.17 on 2026-09-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_scope1_12_domains'),
        ('leases', '0001_scope1_12_domains'),
        ('parties', '0001_scope0_foundation'),
        ('property', '0002_alter_asset_id_alter_building_id_alter_contractor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_offers', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='offer',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='parties.party'),
        ),
        migrations.AddField(
            model_name='offer',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='property.space'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='parties.party'),
        ),
        migrations.AddField(
            model_name='offer',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='crm.opportunity'),
        ),
    ]
