# Generated by Django 5.2.17 on 2026-09-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('module', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('management', 'Rəhbərlik'), ('reception', 'Reception'), ('service_desk', 'Service Desk'), ('property_fm', 'Property / FM'), ('resident_user', 'Rezident')], db_index=True, max_length=32)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='rbac.permissioncode')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
